name: ECS Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  REGION: us-west-2
  REPOSITORY: wsc-cicd-ecr
  CLUSTER: wsc-cicd-ecs-cluster
  SERVICE: wsc-cicd-ecs-svc
  TASK_FAMILY: wsc-cicd-ecs-taskdef
  CONTAINER: wsc-cicd-ecs-cnt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Determine Image Tag
        id: tag
        shell: bash
        run: |
          CURRENT=$(aws ecr describe-images \
            --repository-name "$REPOSITORY" \
            --region "$REGION" \
            --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]' \
            --output text 2>/dev/null)

          if [[ "$CURRENT" == "None" || -z "$CURRENT" ]]; then
              TAG="v1.0.0"
          else
              VERSION=${CURRENT#v}
              IFS='.' read MAJOR MINOR PATCH <<< "$VERSION"
              PATCH=$((PATCH+1))
              TAG="v${MAJOR}.${MINOR}.${PATCH}"
          fi

          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          IMAGE=$REGISTRY/$REPOSITORY:$IMAGE_TAG

          docker build -t $IMAGE .
          docker push $IMAGE

          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV

      - name: Register New Task Definition & Update ECS Service
        run: |
          aws ecs describe-task-definition \
            --task-definition $TASK_FAMILY \
            --query taskDefinition \
            > raw_taskdef.json

          jq --arg IMAGE "$IMAGE_URI" \
            'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) | .containerDefinitions[0].image = $IMAGE' \
            raw_taskdef.json > taskdef.json

          NEW_TASK_ARN=$(aws ecs register-task-definition --cli-input-json file://taskdef.json --query "taskDefinition.taskDefinitionArn" --output text)

          aws ecs update-service \
            --cluster $CLUSTER \
            --service $SERVICE \
            --task-definition $NEW_TASK_ARN \
            --force-new-deployment

      - name: Verify Deployment Status
        shell: bash
        run: |
          aws ecs describe-services \
            --cluster "$CLUSTER" \
            --services "$SERVICE" \
            --query "services[0].deployments[*].[status,rolloutState]" \
            --output table